### ISSUE TITLE
Need help with PassTicket for FTP to z/OS system.

### ISSUE THREAD

**Issue by trinhhuynguyen** [chrrel/racf-passticket-generator#1]
I used to following information to generate my pass ticket on my linux LPAR as below:
```

//FTP logon, the APPNAME is usually default to 'OMVSAPPL' set up by z/OS USS.
var passTicket = pt.generateSync("userid", "OMVSAPPL", "xxxxxxxxxxxxxxx");

```

In the z/OS system, I set up PTKTDATA profiles OMVSAPPL and OMVSAPPL.BLAU as shown below, after I used the pass ticket generated on the system above as the 'password' to 'sftp' to the z/OS system with the profiles setup. It said my password, which is the pass ticket was invalid. I checked the UTC times between my linux system and the z/OS system, they are only 1 minute difference. Would you like to check what else I missed here. Thank you so much.

```

CLASS      NAME                                                                          
-----      ----                                                                          
PTKTDATA   OMVSAPPL.BLAU                                                                 
                                                                                         
LEVEL  OWNER      UNIVERSAL ACCESS  YOUR ACCESS  WARNING                                 
-----  --------   ----------------  -----------  -------                                 
 00    M16SPEC         NONE              ALTER    NO                                     
                                                                                         
..                                                    
AUDITING                                                                                 
--------                                                                                 
FAILURES(READ)                                                                           
                                                                                         
GLOBALAUDIT                                                                              
-----------                                                                              
NONE                                                                                     
                                                                                         
NOTIFY                                                                                   
------                                                                                   
NO USER TO BE NOTIFIED                                                                   
                                                                                         
CREATION DATE  LAST REFERENCE DATE  LAST CHANGE DATE                                     
 (DAY) (YEAR)       (DAY) (YEAR)      (DAY) (YEAR)                                       
-------------  -------------------  ----------------                                     
  125    20          125    20         125    20                                         
                                                                                         
ALTER COUNT   CONTROL COUNT   UPDATE COUNT   READ COUNT                                  
-----------   -------------   ------------   ----------                                  
  000000         000000         000000         000000                                    
                                                                                         
USER      ACCESS   ACCESS COUNT                                                          
----      ------   ------ -----                                                          
M16SPEC   ALTER       000000                                                             
BLAU      ALTER       000000                                                             
                                                                                         
   ID     ACCESS  ACCESS COUNT  CLASS                   ENTITY  NAME                     
-------- -------  ------------ -------- ---------------------------------------          
NO ENTRIES IN CONDITIONAL ACCESS LIST                                                    
***           


```
**I also added this:**
```
 CLASS      NAME                                                                                  
 -----      ----                                                                                  
 PTKTDATA   OMVSAPPL                                                                              
                                                                                                  
 LEVEL  OWNER      UNIVERSAL ACCESS  YOUR ACCESS  WARNING                                         
 -----  --------   ----------------  -----------  -------                                         
  00    M16SPEC         NONE              ALTER    NO                                             
                                                                                                  
 INSTALLATION DATA                                                                                
 -----------------                                                                                
 NONE                                                                                             
                                                                                                  
...                                                                                                                                                   
 CREATION DATE  LAST REFERENCE DATE  LAST CHANGE DATE                                             
  (DAY) (YEAR)       (DAY) (YEAR)      (DAY) (YEAR)                                               
 -------------  -------------------  ----------------                                             
   125    20          125    20         125    20                                                 
                                                                                                  
 ALTER COUNT   CONTROL COUNT   UPDATE COUNT   READ COUNT                                          
 -----------   -------------   ------------   ----------                                          
   000000         000000         000000         000000                                            
                                                                                                  
 USER      ACCESS   ACCESS COUNT                                                                  
 ----      ------   ------ -----                                                                  
 M16SPEC   ALTER       000000                                                                     
 BLAU      ALTER       000000                                                                     
                                                                                                  
    ID     ACCESS  ACCESS COUNT  CLASS                   ENTITY  NAME                             
 -------- -------  ------------ -------- ---------------------------------------                  
 NO ENTRIES IN CONDITIONAL ACCESS LIST                                                            

```

The commands I used are below for the OMVSAPPL.BLAU profile. I repeated for OMVSAPPL profile as well.
RDEFINE PTKTDATA OMVSAPPL.BLAU SSIGNON(KEYMASKED(xxxxxxxxxxxxxx))
RALTER  PTKTDATA OMVSAPPL.BLAU APPLDATA('NO REPLAY PROTECTION')   
RLIST PTKTDATA OMVSAPPL.BLAU ALL    
SETROPTS RACLIST (PTKTDATA) REFRESH

**Comment by chrrel** [comment]
Hi @trinhhuynguyen,

unfortunately, I cannot help you directly with your question as I neither can verify your settings nor do I have access to a z/OS system. But maybe the following information can give you some hints. At the time when I implemented this project I wrote the following documentation which is adapted from [this document](https://www.redbooks.ibm.com/redbooks/pdfs/sg247610.pdf).

## Activating and Configuring PassTickets on z/OS

To use PassTickets for authentication, RACF (on the z/OS system to authenticate against) must be configured to activate the PassTicket functionality. For this the following RACF TSO commands have to be executed either in a TSO terminal session or by using a batch job.

First, the PTKDATA class which defines all profiles that contain information on PassTickets must be activated. Additionally generic profiles should be activated for making it easier to define profiles protecting PassTicket functions.

```
setropts classact(ptktdata)
setropts raclist(ptktdata)
setropts generic(ptktdata)
```

Every application that shall make use of PassTickets needs a profile in the PTKDATA class associating a secret key with the application name on a particular system. A profile is created with the RDEFINE command which needs the parameters.

* profile-name, the application name to be defined
* key-description, the secured signon application key
*  access-authority, the universal access authority, should always be defined as NONE.

```
RDEFINE PTKTDATA profile-name SSIGNON(key-description) UACC(access-authority)
```

In order to allow using PassTickets from Java applications additional profiles in the PTKDATA class must be defined with the RDEFINE command. These define which users are allowed to use PassTicket functionalities for a certain application and target user ID.

* target-user, the user ID for whom PassTickets are generated or evaluated
* application is the application name protected by this profile (which must be defined with a key in the PTKDATA class)
* UACC(NONE) defines that by default no one can execute PassTicket operations.

`RDEFINE IRRPTAUTH.application.target-user UACC(NONE)`

## FTP Example

Afterwards it is easily possible to login via FTP using a user ID and a valid PassTicket. In line five the user name CHRREL and the PassTicket DSF1P1Z0 are specified as login credentials.

```
ftp -nv testserver.de.ibm.com
Connected to testserver.de.ibm.com.
220-FTP 12:33:43 on 2016-08-03.
220 Connection will close if idle for more than 60 minutes.
ftp> user CHRREL DSF1P1Z0
331 Send password please.
230 CHRREL is logged on.  Working directory is "CHRREL.".
Remote system type is MVS.
ftp> 
```

Always keep in mind that a PassTicket is only valid once (if replay protection is not disabled) so that you need to regenerate your PassTicket for other login attempts.

**Comment by trinhhuynguyen** [comment]
Hi Christian,
Thanks for the response. I will try again with FTP instead.
Do you happen to know if this works with sFTP as well? 
I read this documentation below. Do you happen to know how to check or set OMVSAPPL as app name because the default value may be blanked out. Thanks again.


This is how we chose APPLNAME for FTP:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.icha700/icha700_z_OS_UNIX_applications.htm
For the z/OS® LDAP server, use the job name associated with the LDAP server's started procedure as the name of your PTKTDATA profile.
For other UNIX-based applications, such as the z/OS HTTP Server and the FTP server, that authenticate using the z/OS UNIX __passwd() service, the default application name is OMVSAPPL. Therefore, in most cases, use OMVSAPPL as the name of your PTKTDATA profile. However, because an application might change the default value or use the __passwd_applid() service to specify an explicit value, see your programmer for the correct application name to specify as the name of your PTKTDATA profile.

**Comment by chrrel** [comment]
I'm sorry, but I think I cannot help you with this specific issue. Maybe it is worth reaching out for help in an official IBM support forum.

An other general idea to check the validity of a PassTicket generated by your implementation is to use the code given in the section _Evaluating a generated PassTicket_ in the README.md file.

**Comment by trinhhuynguyen** [comment]
OK. I'm reaching out to them now. Will inform you of what I found out. Thanks.

**Comment by trinhhuynguyen** [comment]
I've got it working now. I has to do with APPNAME that I didn't not specify it correctly. We can close the now. Thanks.
