### ISSUE TITLE
RACF Enhanced PassTickets: New Algorithm.

### ISSUE THREAD

**Issue by trinhhuynguyen** [chrrel/racf-passticket-generator#2]
Hi Christian,
IBM just announced this enhanced algorithm for PassTicket. Would you like to take a look to see if this algorithm needs to be updated. Thank you very much.

The following IBM Change Notification is being planned by z/OS development.
ICN Number: 1774
ICN Name: RACF Enhanced PassTickets
Abstract: 
IBM intends to deliver a future RACF enhancement to support a new PassTicket algorithm option called Enhanced PassTickets.

**Comment by chrrel** [comment]
Thanks for letting me know. Do you have a link to this announcement or any further details?

**Comment by trinhhuynguyen** [comment]
Hi Christian,
Would you check the ICN to see if this algorithm needs to be enhanced. 

ICN Technical Owner:  Ross D Cooper/Poughkeepsie/IBM
ICN Technical Owner email:  rdc@us.ibm.com
Date IBM Change Notification was written:  07/08/2020
Date IBM Change Notification was approved:  07/30/2020

**Comment by chrrel** [comment]
Hi, it seems like this link is not publicly accessible ...

**Comment by trinhhuynguyen** [comment]
Hi Christian,
The owner of the ICN said that it could only be shared with software vendors that are under current non-disclosure agreements with IBM. Thanks.
